server:
  port: 8080

spring:
  application:
    name: sumJeonBok

  security:
    user:
      name: user
      password: 1234

  datasource:
    url: jdbc:mariadb://localhost:3306/sumJeonBok
    username: jaehyung
    password: jaehyung96
    driver-class-name: org.mariadb.jdbc.Driver

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update